# Generated by Django 6.0.5 on 2026-05-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='matrícula',
            new_name='matricula',
        ),
    ]
