# Generated by Django 5.2.14 on 2026-05-12 04:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0003_alter_aluno_id'),
        ('disciplinas', '0002_alter_disciplina_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='disciplinas.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('disciplina', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='disciplinas.disciplina')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('aluno', 'disciplina', 'data')},
            },
        ),
        migrations.CreateModel(
            name='LimiteFaltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria_total', models.IntegerField(help_text='Carga horária em horas')),
                ('percentual_maximo', models.FloatField(default=25.0, help_text='Percentual máximo de faltas (ex: 25%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='disciplinas.disciplina')),
            ],
            options={
                'unique_together': {('disciplina',)},
            },
        ),
        migrations.CreateModel(
            name='PresencaChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='faltas.chamada')),
            ],
            options={
                'unique_together': {('chamada', 'aluno')},
            },
        ),
    ]
