# Generated by Django 6.0.5 on 2026-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_rename_matrícula_aluno_matricula'),
        ('disciplinas', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='valor',
            new_name='nota1',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'disciplina')},
        ),
    ]
